[project]
name = "fintect"
version = "0.1.0"
description = "財經新聞重大消息爬蟲"
readme = "README.md"
authors = [
    { name = "Willseed", email = "jgh98323@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
    "playwright>=1.62.0",
]

[dependency-groups]
dev = [
    "colorama>=0.4.6",
    "isort>=9.0.1",
    "pylint>=4.0.8",
]

[tool.uv]
package = false
required-version = ">=0.12.11"
